spring:
  application:
    name: student-management-api
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management_db
    username: postgres
    password: ${DB_PASSWORD:Piseth1711*#}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
#  cache:
#    type: redis
#    cache-names:
#      - student-by-id
#      - department-by-id
#      - course-by-id
#      - instructor-by-id
#      - course-offering-by-id
#      - external-user-by-id
#      - external-users-page
#app:
#  cache:
#    default-ttl: 10m
#    student-ttl: 10m
#    department-ttl: 30m
#    course-ttl: 20m
#    instructor-ttl: 15m
#    course-offering-ttl: 5m
#    external-user-ttl: 5m
#    external-users-page-ttl: 2m
app:
  cache:
    student:
      key-prefix: "student-management:v1:student:"
      ttl: 10m
    department:
      key-prefix: "student-management:v1:department:"
      ttl: 30m
    course:
      key-prefix: "student-management:v1:course:"
      ttl: 20m
    instructor:
      key-prefix: "student-management:v1:instructor:"
      ttl: 15m
    course-offering:
      key-prefix: "student-management:v1:course-offering:"
      ttl: 5m
    external-user:
      key-prefix: "student-management:v1:external:user:"
      ttl: 5m
    external-post:
      key-prefix: "student-management:v1:external:post:"
      ttl: 5m
    external-comment:
      key-prefix: "student-management:v1:external:comment:"
      ttl: 5m
    external-album:
      key-prefix: "student-management:v1:external:album:"
      ttl: 5m
server:
  port: 8080
security:
  jwt:
    private-key-path: private.pem
    public-key-path: public.pem
    issuer: student-management-api
    expiration-seconds: 3600
    refresh-expiration-seconds: 604800
logging:
  file:
    name: logs/student-management-api.log
  level:
    root: INFO
    com.acleda.training.studentmanagement: INFO
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-NO-REQUEST}] [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-NO-REQUEST}] [%thread] %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: logs/archive/student-management-api-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
third-party:
  json-placeholder:
    base-url: ${JSON_PLACEHOLDER_BASE_URL:https://jsonplaceholder.typicode.com}
    connect-timeout: 3s
    response-timeout: 5s
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    persist-authorization: false
scalar:
  enabled: true
  path: /scalar
  url: /v3/api-docs